version: '3'

services:

  db:
    image: mysql:latest
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kartacadb
      - MYSQL_USER=mefe
      - MYSQL_PASSWORD=mefe123
    ports:
      - "3306:3306"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "topic_kartaca:1:3"

  kartaca-task-app: #it is just a name, which will be used only in this file.
    image: kartaca-task               #name of the image after dockerfile executes
    container_name: kartaca-task-app  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8080:8080"                       #docker container port with your os port
    restart: on-failure

    depends_on: #define dependencies of this app
      - kafka
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/kartacadb
      SPRING_DATASOURCE_USERNAME: mefe
      SPRING_DATASOURCE_PASSWORD: mefe123